tasks:
  - name: denoising

    metrics:
      - name: psnr
      - name: ssim

    preprocessing:
      - name: channels_denoise_preprocessor
        h: 3
        template_window_size: 7
        search_window_size: 21

    datasets:
      - qsd1_w3
