task:
  name: masking
  output_dir: "./output"

  metrics:
    - name: mae
    # - name: avg_mae
    # - name: precision
    # - name: recall
    # - name: f1

  preprocessing:
    - variance_mask_preprocessor
  
datasets:
  - qsd2_w1
