task:
  name: masking
  output_dir: "./output"

  metrics:
    - name: mae
    # - name: avg_mae
    # - name: precision
    # - name: recall
    # - name: f1

  preprocessing:
    - name: combined_mask_preprocessor
      channel: 1

datasets:
  - museum
