tasks:
  - name: masking

    metrics:
      - name: mae
      - name: accuracy
      - name: precision
      - name: recall
      - name: f1

    preprocessing:
      - name: paint_mask_preprocessor
        color_space: hsv
        metric: std
        channel: 1
        # fill_holes: False

    datasets:
      - qsd2_w1
