task:
  name: masking
  output_dir: "./output"

  metrics:
    - name: mae
    - name: accuracy
    - name: precision
    - name: recall
    - name: f1

  preprocessing:
    - name: variance_mask_preprocessor
      channel: 1

datasets:
  - qst2_w1
