task:
  name: retrieval
  output_dir: "./output"

  features_extractor: 
    name: example_extractor
    n_neighbors: 3
    top_k: 3

  metrics:
      - name: raw_accuracy
  #   - name: mae
  #   - name: avg_mae
  #   - name: precision
  #   - name: recall
  #   - name: f1

  # preprocessing:
  #   - name: combined_mask_preprocessor
  #     channel: 0
  
datasets:
  - qsd1_w1
