tasks:  
  - name: retrieval

    # tokenizer:
    #    name: visual_codebook_tokenizer
    #    k_size: 128
    #    num_words: 32

    features_extractor: 
      name: HOG_extractor
      # n_patches: 10
      # channel: 0

    distance:
      name: l1
      n_neighbors: 20

    metrics:
      - name: map
        top_k: [1, 5, 10]

    #preprocessing:
    #  - name: local_variance_mask_preprocessor
    #    channel: 1
  
    datasets:
      - qsd1_w1
  
