task:
  name: retrieval
  output_dir: "./output"

  # tokenizer:
  #    name: visual_codebook_tokenizer
  #    k_size: 128
  #    num_words: 128

  features_extractor: 
    name: local_histogram_extractor
    n_neighbors: 20
    top_k: 5
    n_patches: 30
    channel: 0

  distance:
    name: cosine

  metrics:
    - name: raw_accuracy
    - name: map

  preprocessing:
    - name: variance_mask_preprocessor
      channel: 1
  
datasets:
  - qsd2_w1
