tasks:  
  - name: retrieval

    tokenizer:
      name: bpe_tokenizer
      vocab_size: 256
      fixed_length: 30

    text_distance:
      name: bag_dist
      n_neighbors: 20

    features_extractor: 
      name: zernike_extractor
      n_patches: 10
      channel: 0

    distance:
      name: l1
      n_neighbors: 20

    metrics:
      - name: map
        top_k: [1, 5, 10]

    preprocessing:
      - name: fourier_mask_preprocessor
        channel: 1
      - name: text_detector_wo_mask
  
    datasets:
      - qsd1_w2
  
