task:
  name: retrieval
  output_dir: "./output"

  # tokenizer:
  #   name: visual_codebook_tokenizer
  #   k_size: 128
  #   num_words: 24

  features_extractor: 
<<<<<<< HEAD
    name: local_histogram_extractor
    n_neighbors: 20
=======
    name: hist_rgb_concat_extractor
    n_neighbors: 8
>>>>>>> 684bded1a9840843ff3ea99ad58e0c849ba156e8
    top_k: 3

  distance:
    name: cosine

  metrics:
    - name: raw_accuracy
    - name: euclidian_distance
    - name: l1_distance
    - name: chi2_distance
    - name: hellinger_kernel_distance
    - name: histogram_intersection_similarity
    - name: map
  # preprocessing:
  #   - name: combined_mask_preprocessor
  #     channel: 0
  
datasets:
  - qsd1_w1
