tasks:
  - name: text_detection

    tokenizer:
          name: bpe_tokenizer
          vocab_size: 256

    metrics:
      - name: iou
      - name: text_levenshtein
      - name: text_editex
      - name: text_jaccard

    preprocessing:
      # - name: fourier_mask_preprocessor
      #   color_space: hsv
      #   channel: 1
      - name: text_detector_wo_mask

    datasets:
      - qsd1_w2
